export const GET_SUPERADMINS_PENDING = 'GET_SUPERADMINS_PENDING';
export const GET_SUPERADMINS_SUCCESS = 'GET_SUPERADMINS_SUCCESS';
export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMINS_ERROR';

export const GET_SUPERADMINS_BY_ID_PENDING = 'GET_SUPERADMINSID_PENDING';
export const GET_SUPERADMINS_BY_ID_SUCCESS = 'GET_SUPERADMINSID_SUCCESS';
export const GET_SUPERADMINS_BY_ID_ERROR = 'GET_SUPERADMINSID_ERROR';

export const DELETE_SUPERADMINS_PENDING = 'DELETE_SUPERADMINS_PENDING';
export const DELETE_SUPERADMINS_SUCCESS = 'DELETE_SUPERADMINS_SUCCESS';
export const DELETE_SUPERADMINS_ERROR = 'DELETE_SUPERADMINS_ERROR';

export const ADD_SUPERADMINS_PENDING = 'ADD_SUPERADMINS_PENDING';
export const ADD_SUPERADMINS_SUCCESS = 'ADD_SUPERADMINS_SUCCESS';
export const ADD_SUPERADMINS_ERROR = 'ADD_SUPERADMINS_ERROR';

export const UPDATE_SUPERADMINS_PENDING = 'UPDATE_SUPERADMINS_PENDING';
export const UPDATE_SUPERADMINS_SUCCESS = 'UPDATE_SUPERADMINS_SUCCESS';
export const UPDATE_SUPERADMINS_ERROR = 'UPDATE_SUPERADMINS_ERROR';
