export const GET_SUPERADMINS_PENDING = 'GET_SUPERADMINS_PENDING';
export const GET_SUPERADMINS_SUCCESS = 'GET_SUPERADMINS_SUCCESS';
export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMINS_ERROR';
export const DELETE_SUPERADMINS_PENDING = 'DELETE_SUPERADMINS_PENDING';
export const DELETE_SUPERADMINS_SUCCESS = 'DELETE_SUPERADMINS_SUCCESS';
export const DELETE_SUPERADMINS_ERROR = 'DELETE_SUPERADMINS_ERROR';
