export const GET_CLASSES_PENDING = 'GET_CLASSES_PENDING';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const DELETE_CLASS_PENDING = 'DELETE_CLASS_PENDING';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_ERROR = 'DELETE_CLASS_ERROR';
