export const GET_TRAINERS_PENDING = 'GET_TRAINERS_PENDING';
export const GET_TRAINERS_SUCCESS = 'GET_TRAINERS_SUCCESS';
export const GET_TRAINERS_ERROR = 'GET_TRAINERS_ERROR';

export const GET_TRAINERS_BY_ID_PENDING = 'GET_TRAINERS_BY_ID_PENDING';
export const GET_TRAINERS_BY_ID_SUCCESS = 'GET_TRAINERS_BY_ID_SUCCESS';
export const GET_TRAINERS_BY_ID_ERROR = 'GET_TRAINERS_BY_ID_ERROR';

export const DELETE_TRAINER_PENDING = 'DELETE_TRAINER_PENDING';
export const DELETE_TRAINER_SUCCESS = 'DELETE_TRAINER_SUCCESS';
export const DELETE_TRAINER_ERROR = 'DELETE_TRAINER_ERROR';

export const UPDATE_TRAINER_PENDING = 'UPDATE_TRAINER_PENDING';
export const UPDATE_TRAINER_SUCCESS = 'UPDATE_TRAINER_SUCCESS';
export const UPDATE_TRAINER_ERROR = 'UPDATE_TRAINER_ERROR';

export const ADD_TRAINER_PENDING = 'ADD_TRAINER_PENDING';
export const ADD_TRAINER_SUCCESS = 'ADD_TRAINER_SUCCESS';
export const ADD_TRAINER_ERROR = 'ADD_TRAINER_ERROR';
