export const GET_MEMBERS_PENDING = 'GET_MEMBERS_PENDING';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_ERROR = 'GET_MEMBERS_ERROR';

export const DELETE_MEMBER_PENDING = 'DELETE_MEMBER_PENDING';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_ERROR = 'DELETE_MEMBER_ERROR';

export const GET_MEMBER_BY_ID_PENDING = 'GET_MEMBER_BY_ID_PENDING';
export const GET_MEMBER_BY_ID_SUCCESS = 'GET_MEMBER_BY_ID_SUCCESS';
export const GET_MEMBER_BY_ID_ERROR = 'GET_MEMBER_BY_ID_ERROR';
