export const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';

export const GET_ADMIN_BY_ID_PENDING = 'GET_ADMIN_BY_ID_PENDING';
export const GET_ADMIN_BY_ID_SUCCESS = 'GET_ADMIN_BY_ID_SUCCESS';
export const GET_ADMIN_BY_ID_ERROR = 'GET_ADMIN_BY_ID_ERROR';

export const DELETE_ADMIN_PENDING = 'DELETE_ADMIN_PENDING';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_ERROR = 'DELETE_ADMIN_ERROR';

export const PUT_ADMIN_PENDING = 'PUT_ADMIN_PENDING';
export const PUT_ADMIN_SUCCESS = 'PUT_ADMIN_SUCCESS';
export const PUT_ADMIN_ERROR = 'PUT_ADMIN_ERROR';

export const POST_ADMIN_PENDING = 'POST_ADMIN_PENDING';
export const POST_ADMIN_SUCCESS = 'POST_ADMIN_SUCCESS';
export const POST_ADMIN_ERROR = 'POST_ADMIN_ERROR';
