export const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';

export const GET_ADMINBYID_PENDING = 'GET_ADMINBYID_PENDING';
export const GET_ADMINBYID_SUCCESS = 'GET_ADMINBYID_SUCCESS';
export const GET_ADMINBYID_ERROR = 'GET_ADMINBYID_ERROR';

export const DELETE_ADMIN_PENDING = 'DELETE_ADMIN_PENDING';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_ERROR = 'DELETE_ADMIN_ERROR';
